ansible_become_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34613963353766363136303539653732626461366131636465333764393461346563353438313437
          3266613337636361666238613332616336333733646431650a353434653637326239396433633265
          64663837373333653535326631343337393565663030643939313434306235333361316463613638
          3037323165366433370a643032393433313862346336653636643762306132383436353862306465
          61306538626533323836316662626562353732346132306666306537653666333061